export default async (page) => {
  await page.click('button:has-text("Start workout")')
  await page.waitForURL(/\/workouts\/[0-9a-f-]+$/, { timeout: 30000 })
  await page.selectOption('select[aria-label="Exercise"]', { label: 'Bench Press — Chest' })
  await page.click('button:has-text("Add exercise")')
  await page.waitForSelector('input[aria-label="Set 1 weight"]', { timeout: 20000 })
  await page.fill('input[aria-label="Set 1 weight"]', '60')
  await page.fill('input[aria-label="Set 1 reps"]', '10')
  await page.click('button[aria-label="Mark set 1 done"]')
  await page.waitForTimeout(1000)
  await page.click('button:has-text("Add set")')
  await page.waitForSelector('input[aria-label="Set 2 weight"]', { timeout: 20000 })
  await page.click('button[aria-label="Mark set 2 done"]')
  await page.waitForTimeout(1000)
  await page.click('button:has-text("Finish")')
  await page.waitForTimeout(3000)
}
