/** Polish versions of the demo data (`npm run db:seed -- --lang pl`), keyed by the English text. */
export const PL: Record<string, string> = {
  // Accounts & money
  'Main Bank Account': 'Konto główne',
  'Credit Card': 'Karta kredytowa',
  Savings: 'Oszczędności',
  Cash: 'Gotówka',
  'ETF Portfolio': 'Portfel ETF',
  Rent: 'Czynsz',
  'Orange Internet': 'Internet Orange',
  'Monthly savings': 'Miesięczne oszczędności',
  'Design project': 'Projekt graficzny',
  Bakery: 'Piekarnia',
  'Market value update': 'Aktualizacja wyceny',
  'Fun & shopping': 'Rozrywka i zakupy',
  // Category names (must match the Polish categories created for new users)
  Food: 'Jedzenie',
  Housing: 'Mieszkanie',
  Transport: 'Transport',
  Health: 'Zdrowie',
  Entertainment: 'Rozrywka',
  Shopping: 'Zakupy',
  Travel: 'Podróże',
  Education: 'Edukacja',
  Subscriptions: 'Subskrypcje',
  Utilities: 'Rachunki',
  Other: 'Inne',
  Salary: 'Wynagrodzenie',
  Freelance: 'Zlecenia',
  Investments: 'Inwestycje',
  Gifts: 'Prezenty',
  'Other income': 'Inne przychody',
  // Goals & projects
  'Build emergency fund': 'Fundusz awaryjny',
  'Run a half marathon': 'Przebiec półmaraton',
  'Read 24 books': 'Przeczytać 24 książki',
  'Move to Berlin': 'Przeprowadzka do Berlina',
  'Get AWS certification': 'Certyfikat AWS',
  'Learn Spanish basics': 'Podstawy hiszpańskiego',
  books: 'książek',
  'Run 5 km without stopping': 'Przebiec 5 km bez zatrzymania',
  'Run 10 km': 'Przebiec 10 km',
  'Run 15 km': 'Przebiec 15 km',
  'Race day — 21.1 km': 'Dzień startu — 21,1 km',
  'Find a flat, sort out paperwork and move by spring.':
    'Znaleźć mieszkanie, załatwić formalności i przeprowadzić się do wiosny.',
  'Website redesign': 'Nowa strona internetowa',
  'New portfolio site with case studies.': 'Nowe portfolio ze studiami przypadków.',
  'Home office setup': 'Domowe biuro',
  // Tasks
  'Research Berlin neighborhoods': 'Sprawdzić dzielnice Berlina',
  'Compare neighborhoods': 'Porównać dzielnice',
  'Find apartment': 'Znaleźć mieszkanie',
  'Prepare documents': 'Przygotować dokumenty',
  'Cancel current rental': 'Wypowiedzieć obecny najem',
  'Book transport': 'Zarezerwować transport',
  'Write case study: banking app': 'Napisać case study: aplikacja bankowa',
  'Finish project presentation': 'Dokończyć prezentację projektu',
  'Pay electricity bill': 'Zapłacić za prąd',
  'Call the dentist': 'Zadzwonić do dentysty',
  'Buy groceries': 'Kupić zakupy spożywcze',
  'Renew passport': 'Odnowić paszport',
  'Plan a trip to Lisbon': 'Zaplanować wyjazd do Lizbony',
  'Water the plants': 'Podlać kwiaty',
  'Weekly planning': 'Planowanie tygodnia',
  'Study for AWS exam — module 4': 'Nauka do egzaminu AWS — moduł 4',
  'Pick a standing desk': 'Wybrać biurko do pracy na stojąco',
  'Read “Atomic Habits”': 'Przeczytać „Atomowe nawyki”',
  'Prepare report': 'Przygotować raport',
  'Mom’s birthday': 'Urodziny mamy',
  // Habits & routines
  'Read 20 minutes': 'Czytanie 20 minut',
  'Drink water': 'Picie wody',
  Meditate: 'Medytacja',
  '10k steps': '10 tys. kroków',
  'Push-ups': 'Pompki',
  Gym: 'Siłownia',
  'No sugar': 'Bez cukru',
  Journal: 'Dziennik',
  min: 'min',
  reps: 'powt.',
  'Morning routine': 'Poranna rutyna',
  'Evening shutdown': 'Wieczorne wyciszenie',
  'Wake up, no phone': 'Pobudka bez telefonu',
  'Drink a glass of water': 'Szklanka wody',
  Stretch: 'Rozciąganie',
  'Plan the day': 'Zaplanuj dzień',
  'Review tomorrow': 'Przejrzyj jutro',
  Read: 'Czytanie',
  // Calendar
  'Team standup': 'Daily zespołu',
  'Client call': 'Rozmowa z klientem',
  'Lunch with Kasia': 'Lunch z Kasią',
  Dentist: 'Dentysta',
  'Padel with friends': 'Padel ze znajomymi',
  'Apartment viewing — Kreuzberg': 'Oglądanie mieszkania — Kreuzberg',
  'Weekend in Kraków': 'Weekend w Krakowie',
  'Car service': 'Serwis samochodu',
  'ASO Toyota': 'ASO Toyota',
  'Portfolio review': 'Przegląd portfela',
  'Bistro Mąka': 'Bistro Mąka',
  // Workouts
  'Upper body A': 'Góra ciała A',
  'Half Marathon — 12 weeks': 'Półmaraton — 12 tygodni',
  Rest: 'Odpoczynek',
  Intervals: 'Interwały',
  'Easy run': 'Spokojny bieg',
  Strength: 'Siłowy',
  'Long run': 'Długi bieg',
  Mobility: 'Mobilność',
  'Intervals 6×800 m': 'Interwały 6×800 m',
  Padel: 'Padel',
  'Kept the pace for 13 km.': 'Utrzymane tempo przez 13 km.',
  kg: 'kg',
  // Notes
  'Berlin budget': 'Budżet na Berlin',
  '<p>Rent: ~1 400 EUR for 2 rooms in Kreuzberg / Neukölln.</p><ul><li><p>Deposit: 3 months</p></li><li><p>Anmeldung within 14 days</p></li></ul>':
    '<p>Czynsz: ~1 400 EUR za 2 pokoje na Kreuzbergu / Neukölln.</p><ul><li><p>Kaucja: 3 miesiące</p></li><li><p>Anmeldung w ciągu 14 dni</p></li></ul>',
  'Rent: ~1 400 EUR for 2 rooms in Kreuzberg / Neukölln. Deposit: 3 months. Anmeldung within 14 days':
    'Czynsz: ~1 400 EUR za 2 pokoje na Kreuzbergu / Neukölln. Kaucja: 3 miesiące. Anmeldung w ciągu 14 dni',
  'Half marathon pacing': 'Tempo na półmaraton',
  '<p>Target pace 5:40/km. Negative split: first 10 km at 5:45.</p>':
    '<p>Docelowe tempo 5:40/km. Negative split: pierwsze 10 km po 5:45.</p>',
  'Target pace 5:40/km. Negative split: first 10 km at 5:45.':
    'Docelowe tempo 5:40/km. Negative split: pierwsze 10 km po 5:45.',
  'Book ideas': 'Książki do przeczytania',
  'Deep Work. The Psychology of Money': 'Praca głęboka. Psychologia pieniędzy',
  // Journal
  'Busy day of meetings.': 'Dzień pełen spotkań.',
  'Finish the report before lunch.': 'Skończyć raport przed lunchem.',
  'Good long run and productive afternoon.': 'Dobry długi bieg i produktywne popołudnie.',
  'Gym session felt strong.': 'Mocny trening na siłowni.',
  'Too much coffee.': 'Za dużo kawy.',
  'Went to bed too late.': 'Za późno poszłam spać.',
  // Shopping
  Groceries: 'Spożywcze',
  Milk: 'Mleko',
  Eggs: 'Jajka',
  Chicken: 'Kurczak',
  Vegetables: 'Warzywa',
  'Toilet paper': 'Papier toaletowy',
  Dairy: 'Nabiał',
  'Meat & fish': 'Mięso i ryby',
  Produce: 'Warzywa i owoce',
  Household: 'Dom',
}
